version: "3.3"
services:
  front:
    image: ${PROJ_NAME}-frontend:latest
    container_name: ${PROJ_NAME}-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/home/node/app
      - front-volume/:/home/node/app/node_modules
    ports:
      - ${FRONT_DEV_PORT}:3000
      - ${FRONT_PROD_PORT}:5000
    # depends_on:
    #   - back
    tty: true
    restart: always
volumes:
  front-volume:
    name: ${PROJ_NAME}-volume
    driver: local
