apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  # ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: tools-container
          image: ubuntu
          command: ["sleep"]
          args: ["10"]
      restartPolicy: Never
