apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sample-ds-rollingupdate
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  selector:
    matchLabels:
      app: sample-ds-rollingupdate
  template:
    metadata:
      labels:
        app: sample-ds-rollingupdate
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.16
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
