apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sample-ds-ondelete
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: sample-ds-ondelete
  template:
    metadata:
      labels:
        app: sample-ds-ondelete
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.16
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
