apiVersion: v1
kind: Pod
metadata:
  name: sample-labels
  labels:
    lb1: val1
    # an2: 200
    lb2: "200"
spec:
  containers:
    - name: nginx-container
      image: nginx:1.16
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
