apiVersion: v1
kind: Pod
metadata:
  name: sample-hostnetwork
  labels:
    name: sample-hostnetwork
spec:
  hostNetwork: true
  containers:
    - name: sample-hostnetwork
      image: nginx:1.16
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
