apiVersion: v1
kind: Pod
metadata:
  name: sample-workingdir
  labels:
    name: sample-workingdir
spec:
  containers:
    - name: nginx-container
      image: nginx:1.16
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      workingDir: /home/app
