apiVersion: v1
kind: Pod
metadata:
  name: sample-dnspolicy-default
  labels:
    name: sample-dnspolicy-default
spec:
  dnsPolicy: Default
  containers:
    - name: nginx-container
      image: nginx:1.16
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
