apiVersion: v1
kind: Pod
metadata:
  name: sample-dnspolicy-none
  labels:
    name: sample-dnspolicy-none
spec:
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 8.8.8.8
      - 8.8.4.4
    searches:
      - "example.com"
    options:
      - name: ndots
        value: "5"
  containers:
    - name: nginx-container
      image: nginx:1.16
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
