apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    name: sample-pod
spec:
  containers:
    - name: sample-pod
      image: nginx:1.16
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8888
