apiVersion: v1
kind: Pod
metadata:
  name: sample-entrypoint
  labels:
    name: sample-entrypoint
spec:
  containers:
    - name: sample-entrypoint
      image: nginx:1.16
      command:
        - "/bin/sleep" # ENTRYPOINT
      args:
        - "3600"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
