apiVersion: v1
kind: Pod
metadata:
  name: sample-2pods
spec:
  containers:
    - name: nginx-container
      image: nginx:1.16
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
    - name: redis-container
      image: redis:3.2
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
