apiVersion: v1
kind: Pod
metadata:
  name: sample-named-port-pod-80
  labels:
    name: sample-app
spec:
  containers:
    - name: nginx-container
      image: nginx:1.16
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: sample-named-port-pod-81
  labels:
    name: sample-app
spec:
  containers:
    - name: nginx-container
      image: nginx:1.16
      env:
        - name: NGINX_PORT
          value: "81"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - name: http
          containerPort: 81
