apiVersion: v1
kind: Service
metadata:
  name: sample-named-port-service
spec:
  type: ClusterIP
  selector:
    name: sample-app
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: http
