apiVersion: v1
kind: Service
metadata:
  name: sample-clusterip
spec:
  type: ClusterIP
  selector:
    app: sample-deployment
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8000
      targetPort: 80
